### ISSUE TITLE
Document minimum node version and consider increasing support

### ISSUE THREAD

**Issue by oh-wo** [Obehave-testing/cli#7]
# To reproduce
On node 4.2.6
```
obehave --help
/usr/local/lib/node_modules/obehave/obehave.js:24
let port = options.port || process.env.OBEHAVE_PORT;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)
at startup (node.js:136:18)
at node.js:966:3
```

# Todo
* Document minimum node version
* See if we can increase support to earlier node versions

**Comment by BevanR** [comment]
`engines` is the way to specify this; https://docs.npmjs.com/files/package.json#engines

I don't think we should bother writing for older Node versions, unless customers really want that?

I expect it works fine on 6.9 LTS.  We could just set`engines` to that, or work out what the lowest version is that you can actually still run it on; probably [anything with reasonable support for ES6, such as Node 6.5](http://kangax.github.io/compat-table/es6/#node65).
